' Gambas module file

'' Find and load a type of script subroutine to load
Public Sub _call(scriptname As String, type As String) As String

  Dim Paths As String[] = Split(SharedMem[type & "path"], ";")

  If File.Dir(scriptname) <> "" Then
    Return scriptname
  Endif

  For Each s As String In Paths
    If Exist(s &/ ScriptName) Then
      Return s &/ scriptname
    Endif
  Next

  '  If Exist(SharedMem.pwd &/ Scriptname) And If VerifyMimeType(SharedMem.pwd &/ Scriptname) Then
  '    Return SharedMem.pwd &/ ScriptName
  '  Endif

  Return ""

Catch
  Stop

End

